name: generate calibrant and release files

on:
  push:
    tags:
    - '*'

jobs:
  release_calibrante:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3

      - name: install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: generate calibrant files
        run: python3 -m pyFAI_calibrants

      - name: zip calibrants
        run: tar -czf calibrants.tar.gz calibrants

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: calibrants.tar.gz
          allowUpdates: true
          body: "all currently available calibrant files"
