name: generate calibrant files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout git repo
      - uses: actions/checkout@v3

      - name: install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          
      - name: generate calibrant files
        run: python3 -m pyFAI_calibrants

      - name: upload calibrant files
        uses: actions/upload-artifact@v3
        with:
          name: calibrant_files
          path: calibrants
